/**
 * Albums
 */
export const FETCH_ALBUMS_BEGIN = 'FETCH_ALBUMS_BEGIN'
export const FETCH_ALBUMS_SUCCESS = 'FETCH_ALBUMS_SUCCESS'
export const FETCH_ALBUMS_ERROR = 'FETCH_ALBUMS_ERROR'

/**
 * Users
 */
export const FETCH_USERS_BEGIN = 'FETCH_USERS_BEGIN'
export const FETCH_USERS_SUCCESS = 'FETCH_USERS_SUCCESS'
export const FETCH_USERS_ERROR = 'FETCH_USERS_ERROR'

/**
 * Users
 */
export const FETCH_PHOTOS_BEGIN = 'FETCH_PHOTOS_BEGIN'
export const FETCH_PHOTOS_SUCCESS = 'FETCH_PHOTOS_SUCCESS'
export const FETCH_PHOTOS_ERROR = 'FETCH_PHOTOS_ERROR'
